from json import JSONDecodeError

from risk_policy_distillation.models.components.context_generator import (
    ContextGenerator,
)


class Verifier:

    def __init__(self, inference_engine):
        """
        LLM-based component for verifying if a concept is supported by extracted words
        :param llm_component:
        """
        self.inference_engine = inference_engine

        cg = ContextGenerator()

        self.verification_context = cg.generate_verification_context()
        self.verification_prompt = """ 
                                     Text: {text}
                                     Words: {words}
                                     Bulletpoint: {bulletpoint}
                                   """

    def verify(self, bulletpoints, text, words):
        """
        Verifies and filters out bulletpoints which are not supported by the words in the text.
        :param bulletpoints: List of bulletpoint concepts
        :param text: Input text to LLM-as-a-Judge
        :param words: A list of important words generated by a local word-based explainer
        :return: A filtered list of bulletpoints where each is supported words
        """
        verified = []

        for b in bulletpoints:
            messages = [
                {"role": "system", "content": self.verification_context},
                {
                    "role": "user",
                    "content": self.verification_prompt.format(
                        text=text, words=words, bulletpoint=b
                    ),
                },
            ]

            output = self.inference_engine.chat(
                [messages],
                response_format={
                    "type": "object",
                    "properties": {
                        "answer": {
                            "type": "string",
                            "enum": [
                                "Yes",
                                "No",
                            ],
                        },
                    },
                    "required": [
                        "answer",
                    ],
                },
                postprocessors=["json_object"],
            )

            try:
                supported = output[0].prediction["answer"]
                supported = supported == "Yes"
            except JSONDecodeError:
                supported = False

            if supported:
                verified.append(b)

        return verified
